config/routes.rb
Rails.application.routes.draw do
  root 'pins#index'

  resources :pins

  get "session/new" => "sessions#new", as: :sign_in
  post "session" => "sessions#create", as: :authenticate_session

  get "session/destroy" => "sessions#destroy", as: :sign_out

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user

  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pins
  has_secure_password
  paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  before_action :authenticate_user!

  def index
    @pins = @current_user.pins.page(params[:page])
    #@pins = Pin.where(user_id: session[:user_id]).all # only pins for vitaly (or the current_user)
  end

  def new
    @pin = Pin.new
  end

  def create
    @pin = Pin.new params.require(:pin).permit(:photo, :url)
    @pin.user = @current_user
    if @pin.save
      redirect_to root_path, notice: "COOL BRO"
    else
      render :new
    end
  end

  def authenticate_user!

    if signed_in?
      @current_user = User.find session[:user_id]
    else
      redirect_to sign_in_path
    end

  end

  def signed_in?
    if session[:user_id].to_i > 0
      return true
    else
      return false
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    # get credentials from the form
    username = params[:username]
    password = params[:password]

    # find the user
    user = User.find_by username: username

    if user.try(:authenticate, password)

      # store the id in the session
      session[:user_id] = user.id

      # redirect back
      redirect_to root_path

    else
      redirect_to sign_in_path, alert: "Username or Password not foundskty"
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pins</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if @current_user %>
    <p> Hi <%= @current_user.username %></p>
    <p><%= link_to "Sign Out", sign_out_path %></p>
  <% end %>

  <% if alert %>
    <p><%= alert %></p>
  <% end %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pins/index.html.erb
<h1>Pins</h1>

<div class="row">

  <%= link_to "Add New Pin", new_pin_path, class: "btn btn-default pull-right" %>
  <%= paginate @pins %>
</div>

<div class="row">
<% @pins.each do |pin| %>

  <div class="pin col-xs-3">
    <h3><%= pin.user.username %></h3>
    <%= link_to image_tag(pin.photo.url(:thumb), class: "img-responsive"), pin.photo.url(:large) %>
  </div>

<% end %>
</div>

<%= paginate @pins %>

app/views/pins/new.html.erb
<h1>Add new pin</h1>

<%= simple_form_for @pin do |f| %>
  <%= f.input :photo, hint: "Please paste a url with the HTTP", label: "Photo URL" %>
  <%= f.input :url, label: "Link to website (URL)" %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>